language: python
sudo: required
env:
- TOXENV=py27
- TOXENV=py34
install:
- "(!(test -f docker_packages.txt) || (cat docker_packages.txt | xargs sudo apt-get
  install -y))"
- pip install -r requirements_dev.txt
- pip install -r requirements.txt
script: npm run dist
notifications:
  slack:
    secure: jnEnoZU9CQ02P0nEtmq+DryjFwCMLPJm2gvBHyoxrfa9cABYqQ3N9Y+T4hlo0nXj73PO3RN7lyO9xPDJ/ElgU5yl21Ap1XQmvR7JctcQLl5qlOq/2/8hUacyPB9KaMdGtKHnokXf1S3xmoLetYdoXJzs+sb9H7zYrVtddBOMLh85XPs+IOjfe/7aCXoP9YnPQ6FsGsqPh5bdS9j+ZRyI067Iwt3ewfE4Kc7cBNvh3bmfYDVs7qVmRZ42M01GExprpQ9/FzXdNQp6YW12/G7h/8bbFvhLfENiahCth8jKkQgg8HX1vRA72ESfRpjgajopg9bmUlahwu5EqQJQ2OMWEbHM10BDU6DKxJlXFTthcy8Cny/FNyAK4LluLzj3znapxLMLcbGVl/V2DlWKTujHB5ixwyrcd6UD2v4FIPOIIF6HKXvOpT8eXbhc6bEUImw6vJmfjG3xFJ5wXqSY3ehUEYtJFaKOtd32VnE0eh2wSW3EsDufG2hE2Z5OvhBZdEog1bC3iHVMosw6+rWY0R4zAqJ2Rjs6/1Vsei3ZLojuDUQnhgGV1d2VRDO0aFkviREg2V/SP/rvScOFde6WljyOCFFXjKH6/r8w3kmV/gB6e26QAO1jatiTVoNWFkuHtRWwDM+MTeQxTfosmQWBiNZjg0ex6IbxOQ3XCoPovpU9fYY=
    on_success: change
    on_failure: always
deploy:
- provider: releases
  api_key:
    secure: c2OSZGAga02+D12mXKShP5TLOPkfc0rJ7vbITqLx5W42/xY4EKOtrfPp+7RI5L7tBHCTsnnzmTJU8mjYL0MthHeRszBl57WQ5KAGX0y/Vz1kNOCPEdCecOdhf+YXK0cZdmNPC4lzn3b4pFVog8QVzBTZQsG7HngLo25oDhbntGLzMVUyZUDVTUK6WrKsYmIRxlZKyHtCddjkLNMnysp0JHuYorjGd5CdDCdHWnj68cdaupBFS085B+cz4WB6sb4ggmd2QdrE3554Dq0DIOwwYE9AQ3mKiGsxZVzQfjVOJzJGUJVjPiDHlLiET3HKc+EshUmUBsZd4FADkeikT8RrV6yi6a0Izuh4l+cHkp6QJQkrakDrV52rBeB5YX8ajqsy8Kh2ks7VJf72zLy9bai2nOcW+mSWCNmb2sNgx8SpqVU9wHnp3ZzA2CjBYKFUg2zBq7av0gLFr2iELUmd5+W1wNE8C+Vv7o7eyWVtsBXig78Cum3ierkumgfjpW3LwDNR/x+2tSZxZhptwmW+F+A34zPNqCDr/OQ8yl88hhsuy05xyUfFs1rWdPoIscsPwd1gPK4eZtOMrVt3t6PQUPfDepib4QPY5qErZ0Pd4H2kjlh8NCeyMlfOhJK0YCWmswf1Sz0Jj6cYV96V5kMqmggFdtZeIYHWkhOAJxo92P1nedM=
  file_glob: true
  file: dist/phovea_data_sql*.egg
  on:
    tags: true
    repo: phovea/phovea_data_sql
- provider: pypi
  user: caleydo-bot
  password:
    secure: Op0XHQ4PNOCLDV3zIinR+KWuyCgfyuvIdL4KuF6vTIPSMje5s8ga/U7QqHKB86QQNeEDKzn9pwfQU6mRiTnExvYxgf1dM7qjlHOD1B4CuWHCDYFem9EbUaMkkIsGsfd4dP/j5J/QfrXUzkIaX7vpdUwGjDhcWJnizz8LguKCpuwJuybLz6eFBKS36We4PAviXgUvRRGjiR7FU7nVC7Z/1L6Yc2UqsgYdTV+cEDbVo0WFRiseFzIjPCH4ClsFr6CK3hkc7rMoBo2THxmdPysaoOfENEqxFo52D+oNUziJ4vj4G6Aw9u8o8b3kUFlKHY6iDI1B1KzYvgmNQ1mAlzKBQ1iPurGcD9t5fGcyBeMMJHTOE35FpjaKUi8Hwdxe/DqHfINkVp/e18eP42pFe1h9cxXFmU+647/gF2SSoBdfprvgHPvXHvEj+BiGdMnIaugm4bU/7PQMH/DSN2KceTjC4MvxHpYBkY3AFTb/v8s5DaxTPa5DEb9nvuNw4C7og1Qz9Grl3docQvewWsc6romW8QQcxfRgIbRCURnHBWJAigLvu4vSKbqsEF1s3vLEmm/b2wrA9j9qKtmJA9N8Nvgq+moh4wSXMIaPqAU0f/iRif7A3hcl5xGGUJUFTn98RVK70fchLBwquvdTEnvNpO5DUrQbgkqhGRoNnkrmIq1ceHw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: phovea/phovea_data_sql
